version: '3.8'

services:
  mediawiki:
    build:
      context: build
      dockerfile: Dockerfile
    image: mediawiki-docker
    environment:
      VIRTUAL_HOST: example.com
      LETSENCRYPT_HOST: example.com
    volumes:
      - images:/var/www/html/mediawiki/images
    networks:
      - frontend
      - backend
    container_name: mediawiki
    restart: unless-stopped

  database:
    image: mariadb
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend
    container_name: mariadb
    restart: unless-stopped


volumes:
  images:
    name: mediawiki-images
  data:
    name: mariadb-data


networks:
  frontend:
    external: false
    name: nginx-network
  backend:
    external: false
    name: db-network
